server:
  port: 8080
logging:
  file:
    path: /var/logs

spring:
  datasource:
    url: "jdbc:mysql://rm-uf60l4pv61u806ih4vo.mysql.rds.aliyuncs.com:3306/sos"
    username: "root"
    password: "G8SWUspm7QwaNR"
  cache:
    type: redis
  jpa:
    open-in-view: false
  redis:
    host: "127.0.0.1"
    database: 1