server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: dev
  cache:
    type: redis
  data:
    redis:
      repositories:
        enabled: false
  jpa:
    open-in-view: false
    database: postgresql
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: GMT+8
    property-naming-strategy: SNAKE_CASE
  #ddl-auto: validate
  #show-sql: true

  redis:
    host: "127.0.0.1"
    database: 5

  servlet:
    multipart:
      max-file-size: 1024MB
  web:
    resources:
      add-mappings: false

aliyun:
  endpoint: ${OSS_ENDPOINT}
  accessKeyId: ${OSS_ACCESS_KEY_ID}
  accessKeySecret: ${OSS_ACCESS_KEY_SECRET}
  bucketName: sos-oss