spring:
  datasource:
    url: "jdbc:mysql://rm-uf60l4pv61u806ih4vo.mysql.rds.aliyuncs.com:3306/sos"
    username: "root"
    password: "G8SWUspm7QwaNR"

profile:
  needSign: false
  development: true

logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(--){faint} %clr([%15.15t]){faint} %clr([%4.4line]%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    xyz.keriteal.sosapi: debug