server:
  port: 8080
logging:
  file:
    path: /var/logs

spring:
  profiles:
    active: dev
  cache:
    type: redis
  jpa:
    open-in-view: false
    database: mysql

  redis:
    host: "127.0.0.1"
    database: 5

  servlet:
    multipart:
      max-file-size: 1024MB

aliyun:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI5t724sLwGs1gLMSujqQe
  accessKeySecret: bEUPuMxDkCvcF8EI16xMFnBHwV7d0d
  bucketName: sos-oss