spring:
  datasource:
    url: "jdbc:${DB_TYPE:postgresql}://${DB_URL:localhost}:${DB_PORT}/${DB_NAME}"
    username: "${DB_USER}"
    password: "${DB_PASS}"

profile:
  needSign: false
  development: true

logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(--){faint} %clr([%15.15t]){faint} %clr([%4.4line]%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    xyz.keriteal.sosapi: debug